### ISSUE TITLE
Abilities problem?

### ISSUE THREAD

**Issue by GIANTCRAB** [50DKP/FF2-Official#191] opened 2015-01-03 06:17 UTC
**See [this comment](https://github.com/50DKP/FF2-Official/issues/191#issuecomment-69484984) for the latest standings of this issue.**

Hey, 

It looks like there are some issues with Ninja spy's slowmo ability. It causes the player to have infinite jump attacks. 

Here's the console output: 

![untitled](https://cloud.githubusercontent.com/assets/1075708/5601776/f7773968-9352-11e4-8b7c-7ea5b55d8512.png)

I'm using linux SM 1.6.4 snapshot for the server and I used windows SM 1.6.4 snapshot to compile the *.ff2 files and freak_fortress_2.smx. I am also using the latest tf2 items INC.

EDIT: 
Another problem I faced is the demopan's rage. After he used his rage, the overlay will appear for the bosses that rages after him. EG: Demopan uses rage and then he dies after sometime. The next boss is saxton hale. Saxton hale uses rage and demopan's overlay appears for some reason...

**Comment by 50Wliu** [comment] 2015-01-04 15:05
Just to make sure: are you using 1.10.3?

**Comment by GIANTCRAB** [comment] 2015-01-05 00:36
Yep, using 1.10.3. The Stable branch from Github. (Also, the other branches seem to be out of date)

**Comment by 50Wliu** [comment] 2015-01-05 00:58
Blame my Git skills for that.  I'll probably be pushing some commits tomorrow to fix some issues.

**Comment by GIANTCRAB** [comment] 2015-01-05 02:38
Oh and teleportation bug is back (see issue #52 ).

The !ff2 command is buggy. When I select number 3, the number 2 option is selected instead.

**Comment by 50Wliu** [comment] 2015-01-10 22:19
The errors with logs have been fixed.  Could you open another issue with the Demopan problem if it happens again (and with errors if possible)?

**Comment by GIANTCRAB** [comment] 2015-01-11 06:11
I'll give screenshots of all the errors encountered.

![error1](https://cloud.githubusercontent.com/assets/1075708/5694380/c3016e8a-9990-11e4-88c0-04c461028b66.png)
This error comes up on every round but doesn't seem to have any effect on gameplay.

```
if(StrContains(plugin, "freaks/"))  //Prevent plugins/freaks/freak_fortress_2.ff2 from loading if it exists -.-
	{
		strcopy(error, err_max, "There is a duplicate copy of Freak Fortress 2 inside the /plugins/freaks folder.  Please remove it.");
		return APLRes_Failure;
	}
```

What is this line of code even for, I don't have a duplicate copy and it causes FF2 not to load. I've removed it and it works fine. ![directory](https://cloud.githubusercontent.com/assets/1075708/5694499/5b322db2-999a-11e4-93e9-4e1e76b6807e.png)PS: my freak_fortress_2.smx is placed inside a folder and manually loaded. 


ff2_first_round is set to 0 but first round is still hale.

![spasm](https://cloud.githubusercontent.com/assets/1075708/5694507/e39754fc-999a-11e4-9d83-7d0cc9e3d20c.png)
Slow motion is still bugged, all players will have spasm when slow mo is activated. Spasm does not show up any errors in console. Thankfully, the spasm ends when the slow mo ends. (I forgot to report about the spasm in the first post) ![stucked](https://cloud.githubusercontent.com/assets/1075708/5694498/29396d20-999a-11e4-80bf-c4d68507546d.png) Ninjaspy gets stuck easily due to the spasm. 
The hale untimed/infinite jump attacks is fixed though :+1: 

![error2](https://cloud.githubusercontent.com/assets/1075708/5694515/bf7b7642-999b-11e4-977e-041f65678c33.png)
Seeman's rage explosion doesn't cause any explosion and causes him to be stuck there infinitely. Console error:
![error2 1](https://cloud.githubusercontent.com/assets/1075708/5694516/c46b00f0-999b-11e4-9402-18623c1c1c0a.png)

**Comment by 50Wliu** [comment] 2015-01-11 15:20
I don't even get how all of this is happening.  It was fine in my tests.

**Comment by 50Wliu** [comment] 2015-01-11 15:34
Bugs 4b (Ninja Spy getting stuck) and 5 should be fixed.  Looking into 3 now, and I'll need an unmodified version of FF2 to get the correct stack trace of 1 (sorry).

**Comment by 50Wliu** [comment] 2015-01-11 15:40
For bug 3: The schematics of how `ff2_first_round` works recently changed (see #157).  This broke backwards compatibility (something that I didn't notice).  I'll fix this by marking `ff2_first_round` as deprecated and create a new cvar called `ff2_arena_rounds`.

**Comment by 50Wliu** [comment] 2015-01-11 15:55
Fixed bug 3.  I suggest that you switch over to `ff2_arena_rounds` (where setting it to `1` will have the same effect as `ff2_first_round 0`) since `ff2_first_round` will be going away in v2.

**Comment by GIANTCRAB** [comment] 2015-01-12 01:32
Uh, I modified it by removing those lines I have quoted in bug 2.

I wanted to disable ff2 first round because Freak Fortress 2 1st round always seems to be buggy. The hale sometimes don't have hale jump in the 1st round, pretty odd.

**Comment by 50Wliu** [comment] 2015-01-12 01:44
I'm thought that that had been fixed for some time.  If it hasn't, open up another bug :).

**Comment by GIANTCRAB** [comment] 2015-01-12 13:53
>Could you retest bug 2 using the latest commit? I was attempting to call Debug() there which wasn't initialized at that point and caused the whole plugin to crash.

I was already using commit 779b28826d77a6c16cb6550506458b1e9ea967bb when reporting the issues on issuecomment-69484984

**Comment by GIANTCRAB** [comment] 2015-01-14 11:44
Bug 2 seems to be fixed, I've opened up another issue #195

**Comment by 50Wliu** [comment] 2015-01-14 12:18
I probably messed everything up when trying to satisfy sarysa.  Will fix today.

**Comment by 50Wliu** [comment] 2015-01-16 23:21
I think I've reproduced the slow-mo spasm.

**Comment by 50Wliu** [comment] 2015-01-31 21:49
I can no longer reproduce the slow-mo spasm so I assume that's fixed.

I have however reproduced the demopan rage bug (it's even buggier than you reported ;_;), looking into it now.

**Comment by shadow93** [comment] 2015-02-02 06:08
aaaaaaaaand Demopan's overlay portion of his tradespam rage is completely broken now.

I just simply reverted to using the code from the 1.10.3 version.

**Comment by 50Wliu** [comment] 2015-02-02 14:15
Yup, realized that.  Apparently FakeClientCommand doesn't work for these purposes.

**Closed** 2015-02-02 21:15 UTC
Labels: bug-minor
