### ISSUE TITLE
Boss gets stuck when takes damage?

### ISSUE THREAD

**Issue by lightsth06** [50DKP/FF2-Official#531] opened 2021-08-04 13:31 UTC
https://user-images.githubusercontent.com/88441340/128189480-1c97703f-c371-4071-9ed4-8b1949cf8ccd.mp4

**Comment by naydef** [comment] 2021-08-04 14:21
Hello. Please check the _error logs_ for ff2-related messages. I believe this issue happens when when _FF2 is incorrectly installed_.
Other possible reason is _bad subplugins_.

**Comment by naydef** [comment] 2021-08-09 12:13
I assume the issue is fixed, closing.

**Closed as completed by naydef** 2021-08-09 12:13 UTC
Labels: question
