### ISSUE TITLE
Using DR kills bosses and players instantly

### ISSUE THREAD

**Issue by M76030** [50DKP/FF2-Official#181] opened 2014-12-14 13:26 UTC
Like the Title says, whenever a hale or a normal player is using the deadringer, he will be killed instandly after the fake death
I have the 1.10.3 version of FF2 and the latest SM and MM version
I will provide a error log here from the server console soon enough (if there is an error in the console of course)

**Comment by shadow93** [comment] 2015-01-03 16:57
It's also affecting 1.10.4 as well.

**Comment by 50Wliu** [comment] 2015-01-04 15:05
I'll be fixing this soon (now that I'm back from vacation).

**Comment by shadow93** [comment] 2015-01-19 22:59
In my case, it turns out it was another plugin causing this bug. When i removed said plugin, the DR issues ceased to occur.

**Comment by 50Wliu** [comment] 2015-02-09 16:03
I actually hit this once on the dev server when I was a boss, so re-opening just to be safe.

**Comment by 50Wliu** [comment] 2015-02-27 22:11
Haven't been able to reproduce since, so closing again :P.

**Closed by 50Wliu** 2015-02-27 22:11 UTC
Labels: bug-major
