### ISSUE TITLE
Some errors with music and other

### ISSUE THREAD

**Issue by Hemen353** [50DKP/FF2-Official#399] opened 2016-06-03 17:41 UTC
I found some errors:
I have everything updated.
```
L 06/03/2016 - 13:30:01: [SM] Native "TF2Items_SetFlags" reported: Invalid TF2ItemType handle 14793cba (error 3)
L 06/03/2016 - 13:30:01: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 06/03/2016 - 13:30:01: [SM]   [0]  Line 3699, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::PrepareItemHandle()
L 06/03/2016 - 13:30:01: [SM]   [1]  Line 3634, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::TF2Items_OnGiveNamedItem()
```
```
L 06/03/2016 - 14:50:01: [SM] Native "KillTimer" reported: Invalid timer handle 37753ce6 (error 3)
L 06/03/2016 - 14:50:01: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 06/03/2016 - 14:50:01: [SM]   [0]  Line 2981, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::StopMusic()
L 06/03/2016 - 14:50:01: [SM]   [1]  Line 2569, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::OnRoundEnd()
```
```
L 06/03/2016 - 17:12:17: [SM] Native "KillTimer" reported: Invalid timer handle a6253cdb (error 3)
L 06/03/2016 - 17:12:17: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 06/03/2016 - 17:12:17: [SM]   [0]  Line 1546, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::DisableFF2()
L 06/03/2016 - 17:12:17: [SM]   [1]  Line 1426, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::OnMapEnd()
```
```
L 06/03/2016 - 17:42:51: [SM] Native "GetEntProp" reported: Entity 9 (9) is invalid
L 06/03/2016 - 17:42:51: [SM] Displaying call stack trace for plugin "freak_fortress_2.smx":
L 06/03/2016 - 17:42:51: [SM]   [0]  Line 601, C:\50DKP\FF2\addons\sourcemod\scripting\include\entity_prop_stocks.inc::GetClientButtons()
L 06/03/2016 - 17:42:51: [SM]   [1]  Line 521, C:\50DKP\FF2\addons\sourcemod\scripting\include\freak_fortress_2.inc::FF2_ShowSyncHudText()
L 06/03/2016 - 17:42:51: [SM]   [2]  Line 2490, C:\50DKP\FF2\addons\sourcemod\scripting\freak_fortress_2.sp::BossInfoTimer_ShowInfo()
```

I know nothing about programming.

**Comment by naydef** [comment] 2016-06-03 18:06
FF2 version(because I suspect it's too old)! If it's old, update to the current versionI suspect your SM installation is corrupted

**Comment by 50Wliu** [comment] 2016-06-03 20:30
No, this is the latest FF2 version (I know because of the directory path).

**Comment by 50Wliu** [comment] 2016-07-24 17:20
I believe these have all been fixed.  Except maybe for the first one.  Closing until they can be reproduced on at least f3f7399.

**Closed by 50Wliu** 2016-07-24 17:20 UTC
Labels: bug-minor
