### ISSUE TITLE
Bugs with Companions

### ISSUE THREAD

**Issue by M76030** [50DKP/FF2-Official#259] opened 2015-06-04 11:37 UTC
Well, when i was on my server i had these bugs with the companions:

1. They always have 1 lives, even if i set in their configs more lives:
for example my F2P Demoman and Soldier Duo, while the Soldier one has 2 lives (hes the first boss), the Demoman has only 1 life even if it says 2 lives in his config

2. The Companions spawns with no Weapon and as a Scout:
When i was on my server to play just for fun, i found this bug, every time i was the hale and the hale was a duo hale, my partner was a scout with no weapons, everything other was apperantly working, but when a bot was a duo hale, the companion didnt spawn at all.

Im using the latest version of SM and MM aswell as the latest TF2items plugin version, im using 1.10.6 beta.

The arent any errors in the server console.

**Comment by shadow93** [comment] 2015-06-05 02:08
YES.

THIS IS EXACTLY THE BUG IM DEALING WITH!

**Comment by shadow93** [comment] 2015-06-05 02:11
#1 can be easily reproduced on my server.
#2 is a result of MakeBoss not firing for the companion.

**Comment by shadow93** [comment] 2015-06-06 03:10
It looks like FindCompanion is derping somewhere

**Comment by shadow93** [comment] 2015-06-06 03:13
From the looks of it, ParseFormula might be derping for companions for the HP issue.

**Comment by 50Wliu** [comment] 2015-06-11 21:21
I believe I've already fixed issue 2 (at least, I just had a companion bot spawn fine).
Trying to pinpoint what's going wrong with 1).

**Comment by 50Wliu** [comment] 2015-06-18 21:24
I can no longer reproduce any of these issues.  @M76030, @shadow93 can you confirm?

**Comment by shadow93** [comment] 2015-06-20 04:35
Can no longer reproduce the companion lives bug anymore.

**Comment by 50Wliu** [comment] 2015-06-20 14:28
Closing this then until I get feedback that this is still broken.

**Closed by 50Wliu** 2015-06-20 14:28 UTC
Labels: bug-major, needs-reproduction
